#! /usr/bin/perl -w
use strict;
use warnings;
print "What do you want to do with each \$file?\n";
chomp (my $choice = <STDIN>);
print "Your choice is $choice\n";
if ($choice =~ /mtann/) {
    foreach my $file (@ARGV) {
	my $line = $choice . "-i ". $file ." -o " . $file.".all";
	print $line;
	system $line;
	}
}
else {
    foreach my $file (@ARGV) {
	system "$choice $file";
    }
}

print "Done!\n";
