#!/usr/bin/python

import datetime
import os
import sys
import string
import argparse
from Bio import SeqIO
import MySQLdb as mdb

import warnings
warnings.filterwarnings("ignore")

parser = argparse.ArgumentParser()
parser.add_argument("file", help="input fasta file")
parser.add_argument("table", help="MySQL table name")

args = parser.parse_args()
fastaFile = args.file
table = args.table

species = raw_input("Species name: ")

user = raw_input("MySQL Username: ")
password = getpass.getpass()

con = mdb.connect('localhost',user,password,'ngs')
cur = con.cursor()

command = 'DROP TABLE '+table
try:
	cur.execute(command)
except:
	pass
command = sql = 'CREATE TABLE '+table+' (id TEXT, seq LONGTEXT, PRIMARY KEY (id(30)))'
cur.execute(command)

print "Adding '"+table+"' to database 'ngs'..."
handle = open(fastaFile, "rU")
for record in SeqIO.parse(handle, "fasta") :
	command = 'insert into '+table+' VALUES("'+str(record.id)+'","'+str(record.seq)+'")'
	cur.execute(command)

os.system("makeblastdb -in "+fastaFile+" -dbtype nucl -title "+table+" -out /db/blast/"+table)
date = str(datetime.date.fromtimestamp(os.path.getmtime(fastaFile)))
command = 'insert into metadata (db,species,date) VALUES("'+table+'","'+species+'","'+date+'")'

cur.execute(command)
con.commit()
con.close()
