#!/usr/bin/python

import datetime
import os
import sys
import string
import argparse
from Bio import SeqIO
import MySQLdb as mdb
import getpass

import warnings
warnings.filterwarnings("ignore")

parser = argparse.ArgumentParser()
parser.add_argument("table", help="MySQL table name")

args = parser.parse_args()
table = args.table

user = raw_input("MySQL Username: ")
password = getpass.getpass()

con = mdb.connect('localhost',user,password,'ngs')
cur = con.cursor()

command = 'DROP TABLE '+table
try:
	cur.execute(command)
except:
	pass

print "Removed '"+table+"' from database 'ngs'..."

os.system("rm -f /db/blast/"+table+"*")
command = 'delete from metadata where db="'+table+'"'

cur.execute(command)
con.commit()
con.close()
