#!/usr/bin/perl
use strict;
use Bio::SeqIO;
my $reader=new Bio::SeqIO(-format=>'fasta',-file=>shift);
while (my $seq=$reader->next_seq)
{
	print join("\t",$seq->id,$seq->length),"\n";
	my $outfile = $seq->id."_".$seq->length.".fa";
    	my $out = Bio::SeqIO->new(-file => ">$outfile",-format => "fasta");
	$out->write_seq($seq);
}

